package kg.geektech.game.players;

public enum SuperAbility {
    HEAL, BOOST, CRITICAL_DAMAGE, SAVE_DAMAGE_AND_REVERT, BASH, GOLEM_BLOCK, REVIVAL, INVISIBILITY, SUMMON, HACK,
    OSCAR, ANTS_SUPER_ABILITY, DEKU_SUPER_ABILITY,
}
